[basic]
mode = "local"
data_dir = 'D:\Project\temp\kirine-client\data'
log_dir = 'D:\Project\temp\kirine-client\logs'
model_dir = 'D:\Project\temp\kirine-client\models'

[remote]
api_url = ""
api_token = ""

[training]
prepared_base_models = [
    "qwen3_tts:1.7B",
    "qwen3_tts:0.6B",
    "vox_cpm2:2B",
]
hardware_type = "cuda"
attn_implementation = "sdpa"
lora_mode = "disabled"
lora_rank = 16
lora_alpha = 32
lora_dropout = "0.05"
