[basic]
mode = "local"
data_dir = 'D:\Project\temp\kirine-client\data'
log_dir = 'D:\Project\temp\kirine-client\logs'
model_dir = 'D:\Project\temp\kirine-client\models'

[remote]
api_url = ""
api_token = ""

[training]
hardware_type = "cpu"
attn_implementation = "sdpa"
